Repository codeit-sprint-fullstack/6-sprint-mission-fe, pull requests merged in 2025-04, with the labels that each got.

#169 [김승준] sprint8
  .gitignore
  jsconfig.json
  next.config.js
  package-lock.json
  package.json
  postcss.config.mjs
  public/img/Img_home_01.png
  public/img/Img_home_02.png
  public/img/Img_home_03.png
  public/img/Img_reply_empty.png
  public/img/best_badge.png
  public/img/google.png
  public/img/home_bottom.png
  public/img/home_top.png
  public/img/ic_facebook.png
  public/img/ic_instagram.png
  public/img/ic_profile.png
  public/img/ic_twitter.png
  public/img/ic_youtube.png
  public/img/kakao.png
  public/img/logo.png
  public/img/making.png
  public/img/mobile_logo.png
  public/img/pavicon.png
  src/app/HomePage.module.css
  src/app/articles/[id]/edit/page.jsx
  src/app/articles/[id]/page.jsx
  src/app/articles/createArticle/page.jsx
  src/app/articles/page.jsx
  src/app/globals.css
  src/app/items/page.jsx
  src/app/items/style.module.css
  src/app/layout.jsx
  src/app/not-found.jsx
  src/app/page.jsx
  src/components/DropDown.jsx
  src/components/Filters.jsx
  src/components/LikeToArticle.jsx
  src/components/LikeToProduct.jsx
  src/components/Pagination.jsx
  src/components/Search.jsx
  src/components/articles/ArticleDetail.jsx
  src/components/articles/ArticleList.jsx
  src/components/articles/Articles.jsx
  src/components/articles/BestArticles.jsx
  src/components/articles/Card.jsx
  src/components/comments/_article/commentsection.jsx
  src/components/css/filters.module.css
  src/components/css/like.module.css
  src/components/css/pagination.module.css
  src/components/css/search.module.css
  src/components/footer/page.jsx
  src/components/header/page.jsx
  src/components/utils.js
  src/utils/imagePath.js
Labels: 매운맛🔥, 최종 제출

#171 [김단이] Sprint8
  .gitignore
  eslint.config.mjs
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/images/home/bottom-banner-image.png
  public/images/home/feature1-image.png
  public/images/home/feature2-image.png
  public/images/home/feature3-image.png
  public/images/home/hero-image.png
  public/images/icons/eye-invisible.svg
  public/images/icons/eye-visible.svg
  public/images/logo/favicon.ico
  public/images/logo/logo.svg
  public/images/logo/og-image.png
  public/images/macbook.png
  public/images/profile.png
  public/images/reply_empty.png
  public/images/social/Component2.png
  public/images/social/Component3.png
  public/images/social/facebook-logo.svg
  public/images/social/google-logo.png
  public/images/social/instagram-logo.svg
  public/images/social/kakao-logo.png
  public/images/social/twitter-logo.svg
  public/images/social/youtube-logo.svg
  src/api/article.api.js
  src/api/axiosInstance.js
  src/app/board/[id]/edit/page.jsx
  src/app/board/[id]/page.jsx
  src/app/board/new/page.jsx
  src/app/board/page.jsx
  src/app/globals.css
  src/app/layout.jsx
  src/app/page.jsx
  src/components/BestPostCard.jsx
  src/components/BestPosts.jsx
  src/components/CommentItem.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/PostCard.jsx
  src/components/PostContent.jsx
  src/components/PostList.jsx
  src/components/SearchSortBar.jsx
Labels: 매운맛🔥, 최종 제출

#168 [백지연] sprint8
  .github/pull-request-template.md
  .github/workflows/auto-label-assign.yml
  .gitignore
  README.md
  eslint.config.mjs
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/Frame 2609885.svg
  public/Img_reply_empty.svg
  public/btn_medium.svg
  public/headerLogo.svg
  public/ic_arrow_down.png
  public/ic_arrow_down.svg
  public/ic_facebook.svg
  public/ic_heart-1.svg
  public/ic_heart.svg
  public/ic_instagram.svg
  public/ic_kebab.svg
  public/ic_profile.svg
  public/ic_search.svg
  public/ic_twitter.svg
  public/ic_youtube.svg
  public/img_badge.svg
  public/line.svg
  public/line2.svg
  src/app/free-board/[id]/_component/AddCommet.jsx
  src/app/free-board/[id]/_component/Comments.jsx
  src/app/free-board/[id]/_component/DateCalculator.jsx
  src/app/free-board/[id]/_component/DropdownMenu.jsx
  src/app/free-board/[id]/edit/page.jsx
  src/app/free-board/[id]/page.jsx
  src/app/free-board/page.jsx
  src/app/globals.css
  src/app/layout.jsx
  src/app/market/page.jsx
  src/app/page.jsx
  src/app/registration/page.jsx
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
  src/components/ui/Article.jsx
  src/components/ui/BestArticle.jsx
  src/components/ui/Button.jsx
  src/components/ui/Dropdown.jsx
  src/lib/api.js
Labels: 최종 제출

#170 [윤세준] sprint8
  .gitignore
  README.md
  env
  eslint.config.mjs
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/images/home/bottom-banner-image.png
  public/images/home/feature1-image.png
  public/images/home/feature2-image.png
  public/images/home/feature3-image.png
  public/images/home/hero-image.png
  public/images/icons/besticon.png
  public/images/icons/eye-invisible.svg
  public/images/icons/eye-visible.svg
  public/images/logo/favicon.ico
  public/images/logo/logo-sm.svg
  public/images/logo/logo.svg
  public/images/logo/og-image.png
  public/images/products/emptyComment.png
  public/images/products/macbook.png
  public/images/products/userProfile.png
  public/images/social/Component2.png
  public/images/social/Component3.png
  public/images/social/facebook-logo.svg
  public/images/social/google-logo.png
  public/images/social/instagram-logo.svg
  public/images/social/kakao-logo.png
  public/images/social/twitter-logo.svg
  public/images/social/youtube-logo.svg
  src/api/articles.api.js
  src/api/axiosInstance.js
  src/app/articles/[id]/edit/page.jsx
  src/app/articles/[id]/page.jsx
  src/app/articles/createArticle/page.jsx
  src/app/articles/page.js
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/components/Article.jsx
  src/components/ArticleDetail.jsx
  src/components/BestArticles.jsx
  src/components/CommentList.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/createArticle.jsx
Labels: 순한맛🐑, 진행 중 🏃

#167 [김수경] sprint8
  .gitignore
  eslint.config.mjs
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/image/footer/Group.png
  public/image/footer/Group.png:Zone.Identifier
  public/image/footer/ic_instagram.png
  public/image/footer/ic_instagram.png:Zone.Identifier
  public/image/footer/ic_twitter.png
  public/image/footer/ic_twitter.png:Zone.Identifier
  public/image/footer/ic_youtube.png
  public/image/footer/ic_youtube.png:Zone.Identifier
  public/image/header/작은 판다 얼굴.png
  public/image/header/작은 판다 얼굴.png:Zone.Identifier
  public/image/header/판다마켓.png
  public/image/header/판다마켓.png:Zone.Identifier
  public/image/ui/articleBadge.png
  public/image/ui/likeHeart.png
  public/image/ui/macbook.png
  public/image/ui/more.png
  public/image/ui/noComment.png
  public/image/ui/profile.png
  public/image/ui/돋보기.png
  public/image/ui/돋보기.png:Zone.Identifier
  src/app/api/article-list/route.js
  src/app/api/comment-list/route.js
  src/app/articles/[id]/page.jsx
  src/app/articles/page.jsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.js
  src/app/login/page.jsx
  src/app/market/page.jsx
  src/app/page.js
  src/app/posting/[id]/page.jsx
  src/app/posting/page.jsx
  src/components/common/Footer.jsx
  src/components/common/Footer.module.css
  src/components/common/Header.jsx
  src/components/ui/Article.jsx
  src/components/ui/ArticleDetail.jsx
  src/components/ui/ArticleHeader.jsx
  src/components/ui/Articles.jsx
  src/components/ui/BestArticle.jsx
  src/components/ui/BestList.jsx
  src/components/ui/Button.jsx
  src/components/ui/Dropdown.jsx
  src/components/ui/MoreToggle.jsx
  src/components/ui/Search.jsx
  src/components/ui/comment/Comment.jsx
  src/components/ui/comment/Comments.jsx
  src/components/ui/comment/CreateComment.jsx
  src/components/ui/posting/InputField.jsx
  src/lib/api/article.js
  src/lib/api/comment.js
  src/providers/ArticlesProvider.jsx
  src/providers/NavIndexProvider.jsx
Labels: 매운맛🔥, 최종 제출

#186 [임정빈] Sprint8
  .gitignore
  README.md
  eslint.config.mjs
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/facebook.png
  public/file.svg
  public/globe.svg
  public/heart.png
  public/instagram.png
  public/kebab.png
  public/laptop.png
  public/logo.png
  public/medal.png
  public/next.svg
  public/profile.png
  public/search.png
  public/sort.png
  public/textLogo.png
  public/twitter.png
  public/vercel.svg
  public/window.svg
  public/youtube.png
  src/api/articleApi.js
  src/app/article/[id]/_components/Comment.jsx
  src/app/article/[id]/_components/CommentForm.jsx
  src/app/article/[id]/_components/DetailBoard.jsx
  src/app/article/[id]/_components/ToggleMenu.jsx
  src/app/article/[id]/page.jsx
  src/app/article/_components/BestArticle.jsx
  src/app/article/_components/Boards.jsx
  src/app/article/_components/PostForm.jsx
  src/app/article/page.jsx
  src/app/context/article.context.js
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/app/post/page.jsx
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
  src/components/ui/Images.jsx
Labels: 미완성🫠, 진행 중 🏃
