Repository codeit-sprint-fullstack/6-sprint-mission-fe, pull requests merged in 2025-05, with the labels that each got.

#189 [김승준] sprint9
  .http
  README.md
  next.config.js
  package-lock.json
  package.json
  public/img/Img_inquiry_empty.png
  src/app/QueryProvider.js
  src/app/articles/[id]/edit/page.jsx
  src/app/articles/createArticle/page.jsx
  src/app/globals.css
  src/app/items/page.jsx
  src/app/items/style.module.css
  src/app/layout.jsx
  src/app/page.jsx
  src/app/products/[id]/edit/page.jsx
  src/app/products/[id]/page.jsx
  src/app/products/createProduct/page.jsx
  src/app/products/page.jsx
  src/app/signin/page.jsx
  src/app/signup/page.jsx
  src/components/Auth/AuthField.jsx
  src/components/Auth/AuthModal.jsx
  src/components/DeleteModal.jsx
  src/components/DropDown.jsx
  src/components/Dropdownmenu.jsx
  src/components/Filters.jsx
  src/components/FormInput.jsx
  src/components/FormTextarea.jsx
  src/components/ImageUploader.jsx
  src/components/LikeToArticle.jsx
  src/components/LikeToProduct.jsx
  src/components/Pagination.jsx
  src/components/Search.jsx
  src/components/SnsSign.jsx
  src/components/TagInput.jsx
  src/components/articles/ArticleDetail.jsx
  src/components/comments/_article/commentsection.jsx
  src/components/comments/_product/CommentsProducts.jsx
  src/components/css/filters.module.css
  src/components/css/pagination.module.css
  src/components/css/search.module.css
  src/components/header/page.jsx
  src/context/AuthContext.js
  src/features/articles/services/articlesApi.js
  src/features/auth/services/authApi.js
  src/features/auth/services/userApi.js
  src/features/comments/services/commentsApi.js
  src/features/images/imageUpload.js
  src/features/products/services/favorite.js
  src/features/products/services/productsApi.js
  src/hooks/usePaginatedProducts.js
  src/utils/authValidation.js
  src/utils/formValidation.js
  src/utils/formatTimeAgoOrDate.js
Labels: 매운맛🔥, 최종 제출

#193 [백지연] Sprint9
  README.md
  public/btn_visibility_on_24px-1.svg
  public/btn_visibility_on_24px.svg
  public/google.svg
  public/ic_heart-2.svg
  public/img_default.svg
  public/kakao.svg
  public/logo.svg
  src/app/free-board/[id]/_component/AddComment.jsx
  src/app/free-board/[id]/_component/Comments.jsx
  src/app/free-board/[id]/_component/DateCalculator.js
  src/app/free-board/[id]/edit/page.jsx
  src/app/free-board/[id]/page.jsx
  src/app/free-board/page.jsx
  src/app/globals.css
  src/app/layout.jsx
  src/app/login/page.jsx
  src/app/market/[id]/page.jsx
  src/app/market/_component/MarketProduct.jsx
  src/app/market/_component/MarketProductList.jsx
  src/app/market/page.jsx
  src/app/registration/free-board/page.jsx
  src/app/registration/market/page.jsx
  src/app/signup/page.jsx
  src/components/common/Header.jsx
  src/components/ui/Button.jsx
  src/components/ui/Dropdown.jsx
  src/components/ui/Modal.jsx
  src/components/ui/Tag.jsx
  src/lib/api.js
  src/utils/validation.js
Labels: 진행 중 🏃

#192 [김홍섭] Sprint9
  .gitignore
  README.md
  next.config.mjs
  package-lock.json
  package.json
  products.http
  signIn.http
  src/app/actions/product.js
  src/app/articles/[articleId]/comments/page.js
  src/app/articles/[articleId]/route.js
  src/app/articles/route.js
  src/app/comments/[commentId]/route.js
  src/app/community/components/Header.js
  src/app/community/create/page.jsx
  src/app/community/page.jsx
  src/app/components/SubmitButton.jsx
  src/app/components/UserEmailInput.jsx
  src/app/components/UserNicknameInput.jsx
  src/app/components/UserPasswordConfirmInput.jsx
  src/app/components/UserPasswordInput.jsx
  src/app/docs/page.jsx
  src/app/favicon.ico
  src/app/items/[itemId]/components/DetailBody.jsx
  src/app/items/[itemId]/components/DetailContact.jsx
  src/app/items/[itemId]/components/DetailImage.jsx
  src/app/items/[itemId]/edit/page.jsx
  src/app/items/[itemId]/page.jsx
  src/app/items/components/ItemImage.jsx
  src/app/items/components/ItemTitle.jsx
  src/app/items/page.jsx
  src/app/layout.js
  src/app/page.js
  src/app/products/[productId]/comments/page.js
  src/app/products/[productId]/page.js
  src/app/products/[productId]/route.js
  src/app/products/page.js
  src/app/products/route.js
  src/app/signin/page.jsx
  src/app/signup/page.jsx
Labels: 매운맛🔥

#212 [박민규] Sprint10
  src/api/articles.js
  src/api/authService.js
  src/api/fetchClient.js
  src/api/products.js
  src/api/userService.js
  src/app/community/[id]/_components/ArticleSection.jsx
  src/app/community/[id]/_components/CommentForm.jsx
  src/app/community/[id]/_components/CommentItem.jsx
  src/app/community/[id]/_components/CommentList.jsx
  src/app/community/[id]/_components/CommentSection.jsx
  src/app/community/[id]/page.jsx
  src/app/community/_components/BestItem.jsx
  src/app/community/_components/BestList.jsx
  src/app/community/_components/CommonItem.jsx
  src/app/community/_components/SearchSortBar.jsx
  src/app/community/write/page.jsx
  src/app/items/[id]/_components/ProductEditModal.jsx
  src/app/items/[id]/_components/ProductOverview.jsx
  src/app/items/[id]/edit/page.jsx
  src/app/items/[id]/page.jsx
  src/app/items/_components/BestProductList.jsx
  src/app/items/_components/CommonProductList.jsx
  src/app/items/_components/Product.jsx
  src/app/items/registration/_components/ProductForm.jsx
  src/app/items/registration/page.jsx
  src/app/registration/page.jsx
  src/components/comment/CommentItem.jsx
  src/hooks/Article/useArticle.js
  src/hooks/Article/useArticles.js
  src/hooks/Article/useComments.js
  src/hooks/Comment/useComments.js
  src/hooks/Products/useBestProducts.js
  src/hooks/Products/useProducts.js
  src/middleware.js
  src/providers/AuthProvider.jsx
Labels: 매운맛🔥, 최종 제출

#207 [김수경] sprint 10
  .gitignore
  http/article.http
  http/comment.http
  http/favorite.http
  http/product.http
  http/req.http
  http/user.http
  package-lock.json
  package.json
  public/image/ui/addProductImg.png
  public/image/ui/cancelTag.png
  src/app/items/[id]/DetailProduct.jsx
  src/app/items/[id]/page.jsx
  src/app/items/page.jsx
  src/app/login/page.jsx
  src/app/posting/page.jsx
  src/app/registration/page.jsx
  src/app/sign-up/page.jsx
  src/components/commonLayout/Header.jsx
  src/components/ui/article/Comment.jsx
  src/components/ui/common-UI/Dropdown.jsx
  src/components/ui/common-UI/InputField.jsx
  src/components/ui/product/productComment.jsx
  src/components/ui/product/productComments.jsx
  src/lib/article.js
  src/lib/authService.js
  src/lib/comment.js
  src/lib/commentProduct.js
  src/lib/fetchClient.js
  src/lib/product.js
  src/lib/userService.js
  src/providers/AuthProvider.jsx
  src/providers/RouteGuard.jsx
  utils/AuthChecker.js
  utils/checkTokenExp.js
Labels: 매운맛🔥, 최종 제출

#210 [김승준] sprint10
  .http
  package-lock.json
  package.json
  src/app/globals.css
  src/app/products/BestProducts.jsx
  src/app/products/[id]/edit/page.jsx
  src/app/products/[id]/page.jsx
  src/app/products/createProduct/page.jsx
  src/app/products/page.jsx
  src/app/signin/page.jsx
  src/app/signup/page.jsx
  src/components/Filters.jsx
  src/components/ImageUploader.jsx
  src/components/LikeToProduct.jsx
  src/components/Search.jsx
  src/components/comments/_product/CommentsProducts.jsx
  src/components/header/page.jsx
  src/context/AuthContext.js
  src/features/auth/services/authApi.js
  src/features/auth/services/fetchWithRefresh.js
  src/features/auth/services/userApi.js
  src/features/comments/services/commentsApi.js
  src/features/images/imageUpload.js
  src/features/products/services/favorite.js
  src/features/products/services/productsApi.js
  src/utils/getImageUrl.js
Labels: 매운맛🔥, 최종 제출

#209 [김단이] Sprint10
  public/images/img_default.png
  src/api/auth.api.js
  src/api/axiosInstance.js
  src/api/item.api.js
  src/api/user.api.js
  src/app/items/[itemId]/_components/CommentItem.jsx
  src/app/items/[itemId]/_components/ProductInfo.jsx
  src/app/items/[itemId]/edit/page.jsx
  src/app/items/[itemId]/page.jsx
  src/app/items/_components/AllItemsSection.jsx
  src/app/items/_components/BestItemsSection.jsx
  src/app/items/_components/DropdownList.css
  src/app/items/_components/DropdownList.jsx
  src/app/items/_components/ItemCard.jsx
  src/app/items/_components/PaginationBar.jsx
  src/app/items/new/page.jsx
  src/lib/authService.js
  src/lib/fetchClient.js
  src/lib/userService.js
  src/providers/AuthProvider.jsx
Labels: 매운맛🔥, 최종 제출

#216 [오하영] Sprint10
  next.config.mjs
  src/app/(auth)/_components/AuthFooter.jsx
  src/app/(market)/_components/CommentItem.jsx
  src/app/(market)/board/_components/ArticleForm.jsx
  src/app/(market)/board/_components/ArticleList.jsx
  src/app/(market)/board/_components/BestArticleList.jsx
  src/app/(market)/board/page.jsx
  src/app/(market)/items/[id]/_components/ItemContainer.jsx
  src/app/(market)/items/_components/ItemCard.jsx
  src/app/(market)/items/_components/ItemForm.jsx
  src/app/error.js
  src/components/ui/Modal.jsx
  src/const.js
  src/lib/actions/auth.js
  src/lib/actions/product.js
  src/lib/getApi.js
  src/lib/utils/authUtils.js
  src/providers/AuthProvider.jsx
Labels: 최종 제출
