Repository codeit-sprint-fullstack/6-sprint-mission-fe, pull requests merged in 2025-03, with the labels that each got.

#105 [임찬빈] - sprint4
  panda market/.gitignore
  panda market/js/ArticleService.js
  panda market/js/ProductService.js
  panda market/js/login.js
  panda market/js/main.js
  panda market/js/signup.js
  panda market/package-lock.json
  panda market/package.json
Labels: 매운맛🔥, 최종 제출

#100 [김다은] Sprint 4
  ArticleService.js
  ProductService.js
  main.js
  package.json
Labels: 최종 제출

#135 [임찬빈] sprint5
  panda market/.gitignore
  react/.gitignore
  react/README.md
  react/eslint.config.js
  react/index.html
  react/package-lock.json
  react/package.json
  react/src/App.jsx
  react/src/api.js
  react/src/assets/Footer.css
  react/src/assets/Footer.jsx
  react/src/assets/Nav.css
  react/src/assets/Nav.jsx
  react/src/assets/ProductsPage.css
  react/src/assets/ProductsPage.jsx
  react/src/img/Icon.png
  react/src/img/Icon.png:Zone.Identifier
  react/src/img/Logo.png
  react/src/img/Logo.png:Zone.Identifier
  react/src/img/M_Logo.png
  react/src/img/M_Logo.png:Zone.Identifier
  react/src/img/Vector.png
  react/src/img/Vector.png:Zone.Identifier
  react/src/img/btnLeft.png
  react/src/img/btnLeft.png:Zone.Identifier
  react/src/img/btnRight.png
  react/src/img/btnRight.png:Zone.Identifier
  react/src/img/icFacebook.png
  react/src/img/icInstagram.png
  react/src/img/icTwitter.png
  react/src/img/icYoutube.png
  react/src/main.jsx
  react/vite.config.js
Labels: 미완성🫠, 순한맛🐑, 최종 제출

#90 [임정빈] Sprint4
  .gitignore
  articles/articleService.js
  index.html
  main.js
  package-lock.json
  package.json
  products/productService.js
Labels: 매운맛🔥, 최종 제출

#114 [박민규] Sprint5
  .gitignore
  README.md
  eslint.config.js
  font/ROKAF_Sans_Bold.ttf
  font/ROKAF_Sans_Medium.ttf
  font/ROKAF_Slab_Serif_Bold.ttf
  font/ROKAF_Slab_Serif_Medium.ttf
  index.html
  package-lock.json
  package.json
  public/img/Img_home_01.png
  public/img/Img_home_02.png
  public/img/Img_home_03.png
  public/img/Img_home_bottom.png
  public/img/Img_home_top.png
  public/img/google_icon.png
  public/img/ic_facebook.png
  public/img/ic_instagram.png
  public/img/ic_twitter.png
  public/img/ic_youtube.png
  public/img/kakao_icon.png
  public/img/panda_icon.png
  public/img/panda_icon_big.png
  public/img/user_icon.png
  public/vite.svg
  src/app/App.css
  src/app/App.jsx
  src/app/layout/Layout.jsx
  src/app/layout/Layout.module.css
  src/app/layout/ui/Footer.jsx
  src/app/layout/ui/Footer.module.css
  src/app/layout/ui/Header.jsx
  src/app/layout/ui/Header.module.css
  src/main.jsx
  src/pages/community/Community.jsx
  src/pages/error/NotFound.jsx
  src/pages/home/Home.jsx
  src/pages/home/Home.module.css
  src/pages/sign-in/SignIn.jsx
  src/pages/used-market/Index.jsx
  src/pages/used-market/Index.module.css
  src/pages/used-market/api/productFetch.js
  src/pages/used-market/model/BestProductList.jsx
  src/pages/used-market/model/BestProductList.module.css
  src/pages/used-market/model/CommonProductList.jsx
  src/pages/used-market/model/CommonProductList.module.css
  src/pages/used-market/model/Pagination.jsx
  src/pages/used-market/model/Pagination.module.css
  src/pages/used-market/ui/Product.jsx
  src/pages/used-market/ui/Product.module.css
  src/shared/hooks/useDeviceType.ts
  vite.config.js
Labels: 매운맛🔥, 최종 제출

#134 [조성빈] sprint5
  6-sprin-tmission-fe-react/.gitignore
  6-sprin-tmission-fe-react/README.md
  6-sprin-tmission-fe-react/eslint.config.js
  6-sprin-tmission-fe-react/index.html
  6-sprin-tmission-fe-react/package.json
  6-sprin-tmission-fe-react/public/img/Img_home_01.png
  6-sprin-tmission-fe-react/public/img/Img_home_02.png
  6-sprin-tmission-fe-react/public/img/Img_home_03.png
  6-sprin-tmission-fe-react/public/img/Img_home_bottom.png
  6-sprin-tmission-fe-react/public/img/Img_home_top.png
  6-sprin-tmission-fe-react/public/img/google_icon.png
  6-sprin-tmission-fe-react/public/img/ic_facebook.png
  6-sprin-tmission-fe-react/public/img/ic_instagram.png
  6-sprin-tmission-fe-react/public/img/ic_twitter.png
  6-sprin-tmission-fe-react/public/img/ic_youtube.png
  6-sprin-tmission-fe-react/public/img/kakao_icon.png
  6-sprin-tmission-fe-react/public/img/panda_icon.png
  6-sprin-tmission-fe-react/public/img/panda_icon_big.png
  6-sprin-tmission-fe-react/public/img/user_icon.png
  6-sprin-tmission-fe-react/public/vite.svg
  6-sprin-tmission-fe-react/src/app/App.css
  6-sprin-tmission-fe-react/src/app/App.jsx
  6-sprin-tmission-fe-react/src/app/layout/Layout.jsx
  6-sprin-tmission-fe-react/src/app/layout/Layout.module.css
  6-sprin-tmission-fe-react/src/app/layout/ui/Footer.jsx
  6-sprin-tmission-fe-react/src/app/layout/ui/Footer.module.css
  6-sprin-tmission-fe-react/src/app/layout/ui/Header.jsx
  6-sprin-tmission-fe-react/src/app/layout/ui/Header.module.css
  6-sprin-tmission-fe-react/src/main.jsx
  6-sprin-tmission-fe-react/src/pages/error/NotFound.jsx
  6-sprin-tmission-fe-react/src/pages/home/Home.jsx
  6-sprin-tmission-fe-react/src/pages/home/Home.module.css
  6-sprin-tmission-fe-react/src/pages/used-market/Index.jsx
  6-sprin-tmission-fe-react/src/pages/used-market/Index.module.css
  6-sprin-tmission-fe-react/src/pages/used-market/api/productFetch.js
  6-sprin-tmission-fe-react/src/pages/used-market/model/BestProductList.jsx
  6-sprin-tmission-fe-react/src/pages/used-market/model/BestProductList.module.css
  6-sprin-tmission-fe-react/src/pages/used-market/model/CommonProductList.jsx
  6-sprin-tmission-fe-react/src/pages/used-market/model/CommonProductList.module.css
  6-sprin-tmission-fe-react/src/pages/used-market/model/Pagination.jsx
  6-sprin-tmission-fe-react/src/pages/used-market/model/Pagination.module.css
  6-sprin-tmission-fe-react/src/pages/used-market/ui/Product.jsx
  6-sprin-tmission-fe-react/src/pages/used-market/ui/Product.module.css
  6-sprin-tmission-fe-react/src/shared/hooks/useDeviceType.ts
  6-sprin-tmission-fe-react/vite.config.js
  package-lock.json
Labels: 미완성🫠

#129 [오하영] Sprint 5
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/App.js
  src/api/api.js
  src/assets/images/icon/arrow-down.svg
  src/assets/images/icon/arrow-left.svg
  src/assets/images/icon/arrow-right.svg
  src/assets/images/icon/ic-heart.svg
  src/assets/images/icon/ic-profile.svg
  src/assets/images/icon/ic-search.svg
  src/assets/images/icon/ic-sort.svg
  src/assets/images/icon/ic-unheart.svg
  src/assets/images/logo/lg-logo.svg
  src/assets/images/logo/md-logo.svg
  src/assets/images/logo/sm-logo.svg
  src/assets/images/logo/type-logo.svg
  src/assets/images/social/facebook-logo.svg
  src/assets/images/social/google-logo.svg
  src/assets/images/social/instagram-logo.svg
  src/assets/images/social/kakao-logo.svg
  src/assets/images/social/twitter-logo.svg
  src/assets/images/social/youtube-logo.svg
  src/components/BestProduct.css
  src/components/BestProduct.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Header.css
  src/components/Header.js
  src/components/Pagination.css
  src/components/Pagination.js
  src/components/ProductList.css
  src/components/ProductList.js
  src/index.js
  src/styles/global.css
Labels: 매운맛🔥, 최종 제출

#148 [임찬빈] sprint6
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  react/README.md
  react/src/App.jsx
  react/src/assets/ProductsPage.css
  react/src/assets/ProductsPage.jsx
  react/src/img/Icon.png:Zone.Identifier
  react/src/img/Logo.png:Zone.Identifier
  react/src/img/M_Logo.png:Zone.Identifier
  react/src/img/Vector.png:Zone.Identifier
  react/src/img/btnLeft.png
  react/src/img/btnLeft.png:Zone.Identifier
  react/src/img/btnRight.png
  react/src/img/btnRight.png:Zone.Identifier
  react/vite.config.js
  src/App.jsx
  src/api.js
  src/component/BestProducts.css
  src/component/BestProducts.jsx
  src/component/Footer.css
  src/component/Footer.jsx
  src/component/Nav.css
  src/component/Nav.jsx
  src/component/Pagination.css
  src/component/Pagination.jsx
  src/component/ProductFilter.css
  src/component/ProductFilter.jsx
  src/component/ProductList.css
  src/component/ProductList.jsx
  src/img/Icon.png
  src/img/Logo.png
  src/img/M_Logo.png
  src/img/Vector.png
  src/img/icFacebook.png
  src/img/icInstagram.png
  src/img/icTwitter.png
  src/img/icYoutube.png
  src/main.jsx
  src/page/ProductsPage.css
  src/page/ProductsPage.jsx
  vite.config.js
Labels: 미완성🫠, 순한맛🐑
