Repository codeit-sprint-fullstack/6-sprint-mission-fe, pull requests merged in 2025-02, with the labels that each got.

#30 [오하영] Sprint 1&2
  .github/.DS_Store
  .gitignore
  faq.html
  favicon.ico
  icon/.DS_Store
  icon/btn_visibility_off.svg
  icon/btn_visibility_on.svg
  icon/googleBg.svg
  icon/ic_facebook.svg
  icon/ic_instagram.svg
  icon/ic_twitter.svg
  icon/ic_youtube.svg
  icon/kakaotalkBg.svg
  img/.DS_Store
  img/Img_home_01.svg
  img/Img_home_02.svg
  img/Img_home_03.svg
  img/Img_home_bottom.svg
  img/Img_home_top.svg
  index.html
  items.html
  login-signup.css
  login.html
  logo/.DS_Store
  logo/Property 1=Typo.svg
  logo/Property 1=lg.svg
  logo/Property 1=md.svg
  logo/Property 1=sm.svg
  privacy.html
  reset.css
  signup.html
  style.css
Labels: 매운맛🔥, 진행 중 🏃

#3 [김승준] sprint1&2
  README.md
  src/img/Img_home_01.png
  src/img/Img_home_02.png
  src/img/Img_home_03.png
  src/img/google.png
  src/img/home_bottom.png
  src/img/home_top.png
  src/img/ic_facebook.png
  src/img/ic_instagram.png
  src/img/ic_twitter.png
  src/img/ic_youtube.png
  src/img/kakao.png
  src/img/logo.png
  src/img/pavicon.png
  src/index.html
  src/login/login.css
  src/login/login.html
  src/login/reset.css
  src/login/script.js
  src/login/signup.html
  src/reset.css
  src/style.css
Labels: 최종 제출

#21 [박민규] sprint 1 & 2
  README.md
  common.css
  faq.html
  font/ROKAF Sans Bold.ttf
  font/ROKAF Sans Medium.ttf
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/google_icon.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/kakao_icon.png
  img/panda_icon.png
  img/panda_icon_big.png
  index.html
  items.html
  login.css
  login.html
  privacy.html
  reset.css
  signup.css
  signup.html
  style.css
Labels: 매운맛🔥

#35 [김단이] Sprint2
  images/Component 2.png
  images/Component 3.png
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/Property 1=Default.png
  images/Property 1=Typo.png
  images/Property 1=Typo@2x.png
  images/Property 1=Typo@3x.png
  images/Property 1=Variant2.png
  images/Property 1=lg.png
  images/Property 1=lg@2x.png
  images/Property 1=lg@3x.png
  images/Property 1=md.png
  images/Property 1=md@2x.png
  images/Property 1=md@3x.png
  images/Property 1=sm.png
  images/Property 1=sm@2x.png
  images/Property 1=sm@3x.png
  images/Property-1lg.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/logo-text-only.png
  index.html
  login/index.html
  login/login.css
  signup/index.html
  signup/signup.css
  style.css
Labels: 매운맛🔥, 최종 제출

#31 [임찬빈] sprint1&2
  README.md
  panda market/html/faq.html
  panda market/html/items.html
  panda market/html/login.html
  panda market/html/privacy.html
  panda market/img/Img_home_01.png
  panda market/img/Img_home_02.png
  panda market/img/Img_home_03.png
  panda market/img/Img_home_bottom.png
  panda market/img/Img_home_top.png
  panda market/img/Img_mainlogo_.png
  panda market/img/big_logo.png
  panda market/img/ic_facebook.png
  panda market/img/ic_google.png
  panda market/img/ic_instagram.png
  panda market/img/ic_kakao.png
  panda market/img/ic_twitter.png
  panda market/img/ic_youtube.png
  panda market/index.html
  panda market/login.css
  panda market/login.html
  panda market/login.js
  panda market/privacy.html
  panda market/reset.css
  panda market/signup.css
  panda market/signup.html
  panda market/style.css
Labels: 매운맛🔥, 최종 제출

#5 [이태빈] Sprint1,2
  .github/pull-request-template.md
  README.md
  faq.html
  font/ROKAF Sans Bold.ttf
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/googlebtn.svg
  image/ic_facebook.svg
  image/ic_instagram.svg
  image/ic_twitter.svg
  image/ic_youtube.svg
  image/kakaobtn.svg
  image/구경하러가기.svg
  image/눈 off.svg
  image/눈 on.svg
  image/로그인 버튼.svg
  image/판다 로고.svg
  image/판다마켓 Favicon.png
  image/판다마켓 대표 이미지.png
  image/판다마켓 로고.svg
  image/판다마켓 사각형 로고.svg
  index.css
  index.html
  items.html
  login.css
  login.html
  login.js
  privacy.html
  reset.css
  signup.css
  signup.html
  signup.js
Labels: 매운맛🔥, 최종 제출

#8 [김다은] sprint1&2
  Img_home_01.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  README.md
  Vector (1).png
  Vector (2).png
  Vector (3).png
  Vector.png
  eye.png
  google.png
  index.html
  items.html
  kakaotalk.png
  login.html
  login_style.css
  reset.css
  signup.html
  signup_style.css
  style.css
  판다 얼굴.png
Labels: 매운맛🔥, 최종 제출

#9 [임정빈] sprint 1 & 2
  README.md
  imges/Component 2.png
  imges/Component 3.png
  imges/Img_home_01.png
  imges/Img_home_02-1.png
  imges/Img_home_02.png
  imges/Img_home_03.png
  imges/Img_home_bottom.png
  imges/Img_home_top.png
  imges/Property 1=md.png
  imges/Vector.png
  imges/desktop_01.png
  imges/desktop_02.png
  imges/desktop_03.png
  imges/desktop_04.png
  imges/desktop_05.png
  imges/ic_facebook.png
  imges/ic_instagram.png
  imges/ic_twitter.png
  imges/ic_youtube.png
  imges/logo.png
  imges/pweye.png
  index.html
  items.html
  member/login.css
  member/login.html
  member/login.js
  member/signup.html
  member/signup.js
  reset.css
  style.css
  userData.js
Labels: 매운맛🔥

#42 [김수빈] sprint1
  스프린트 미션 1/3_1.png
  스프린트 미션 1/3_2.png
  스프린트 미션 1/3_3.png
  스프린트 미션 1/3_4.png
  스프린트 미션 1/FAQ.html
  스프린트 미션 1/Img_home_02.png
  스프린트 미션 1/Img_home_02@2x.png
  스프린트 미션 1/PrivacyPlolicy.html
  스프린트 미션 1/additional.css
  스프린트 미션 1/hrdLMS_Setup.exe
  스프린트 미션 1/icon_facebook.png
  스프린트 미션 1/icon_instagram.png
  스프린트 미션 1/icon_twitter.png
  스프린트 미션 1/icon_youtube.png
  스프린트 미션 1/item.html
  스프린트 미션 1/layer1_logo.png
  스프린트 미션 1/layer2_background.png
  스프린트 미션 1/login.html
  스프린트 미션 1/panda.css
  스프린트 미션 1/pandamarket.html
  스프린트 미션 1/reset.css
Labels: 매운맛🔥, 제출일 이후 제출한PR, 최종 제출

#62 [오하영] Sprint 3
  auth.js
  faq.html
  icon/.DS_Store
  images/home/bottom-banner.png
  images/home/feature1-img.png
  images/home/feature2-img.png
  images/home/feature3-img.png
  images/home/tablet_01.png
  images/home/top-banner.png
  images/icon/eye-invisible.svg
  images/icon/eye-visible.svg
  images/logo/favicon.ico
  images/logo/lg-logo.svg
  images/logo/md-logo.svg
  images/logo/sm-logo.svg
  images/logo/type-logo.svg
  images/social/facebook-logo.svg
  images/social/google-logo.svg
  images/social/instagram-logo.svg
  images/social/kakao-logo.svg
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  img/.DS_Store
  img/Img_home_01.svg
  img/Img_home_02.svg
  img/Img_home_03.svg
  img/Img_home_bottom.svg
  img/Img_home_top.svg
  index.html
  items.html
  login-signup.css
  login.html
  logo/.DS_Store
  privacy.html
  reset.css
  signup.html
  style.css
  styles/auth.css
  styles/palette.css
  styles/reset.css
  styles/style.css
Labels: 매운맛🔥, 최종 제출

#46 [이태빈] Sprint 3
  README.md
  font/ROKAF_Sans_Bold.ttf
  image/ic_big_panda_logo.svg
  image/ic_eye_off.svg
  image/ic_eye_on.svg
  image/ic_google.svg
  image/ic_kakao.svg
  image/ic_panda_favicon.png
  image/ic_small_panda_logo.svg
  image/img_home_01.png
  image/img_home_02.png
  image/img_home_03.png
  image/img_home_bottom.png
  image/img_home_top.png
  image/img_preview.png
  image/구경하러가기.svg
  image/로그인 버튼.svg
  image/판다마켓 로고.svg
  index.css
  index.html
  login.css
  login.html
  login.js
  module.js
  package.json
  panda/faq/faq.html
  panda/items/items.html
  panda/login/login.css
  panda/login/login.html
  panda/login/login.js
  panda/privacy/privacy.html
  panda/signup/signup.css
  panda/signup/signup.html
  panda/signup/signup.js
  signup.css
  signup.html
  signup.js
Labels: 매운맛🔥, 최종 제출

#70 [임찬빈] sprint3
  panda market/css/login.css
  panda market/css/reset.css
  panda market/css/signup.css
  panda market/css/style.css
  panda market/index.html
  panda market/js/login.js
  panda market/js/signup.js
  panda market/login.html
  panda market/login.js
  panda market/signup.html
Labels: 매운맛🔥, 최종 제출

#64 [김단이] Sprint3
  images/Property 1=Variant1.png
  login/index.html
  login/login.css
  login/login.js
  memo3.txt
  signup/index.html
  signup/signup.css
  signup/signup.js
Labels: 매운맛🔥, 최종 제출

#82 Basic 김수빈 sprint3
  README.md
  스프린트 미션 3/css코드/login.css
  스프린트 미션 3/css코드/modal.css
  스프린트 미션 3/css코드/panda.css
  스프린트 미션 3/css코드/signup.css
  스프린트 미션 3/html코드/FAQ.html
  스프린트 미션 3/html코드/PrivacyPolicy.html
  스프린트 미션 3/html코드/index.html
  스프린트 미션 3/html코드/item.html
  스프린트 미션 3/html코드/login.html
  스프린트 미션 3/html코드/signup.html
  스프린트 미션 3/img/Img_home_02@2x.png
  스프린트 미션 3/img/bottom.png
  스프린트 미션 3/img/btn_not_visible.png
  스프린트 미션 3/img/btn_visible.png
  스프린트 미션 3/img/facebook.png
  스프린트 미션 3/img/google.png
  스프린트 미션 3/img/instagram.png
  스프린트 미션 3/img/kakao.png
  스프린트 미션 3/img/login_logo.png
  스프린트 미션 3/img/logo.png
  스프린트 미션 3/img/main_1.png
  스프린트 미션 3/img/main_2.png
  스프린트 미션 3/img/main_3.png
  스프린트 미션 3/img/top.png
  스프린트 미션 3/img/twitter.png
  스프린트 미션 3/img/youtube.png
  스프린트 미션 3/js코드/login.js
  스프린트 미션 3/js코드/signup.js
Labels: 매운맛🔥, 제출일 이후 제출한PR, 진행 중 🏃

#87 [이태빈] Sprint4
  .github/pull-request-template.md
  .gitignore
  API/article_service.js
  API/main.js
  API/product_service.js
  README.md
  index.css
  index.html
  module.js
  package-lock.json
  package.json
  panda/faq/faq.css
  panda/faq/faq.html
  panda/faq/faq.js
  panda/items/items.css
  panda/items/items.html
  panda/items/items.js
  panda/login/login.css
  panda/login/login.html
  panda/login/login.js
  panda/privacy/privacy.css
  panda/privacy/privacy.html
  panda/privacy/privacy.js
  panda/signup/signup.css
  panda/signup/signup.html
  panda/signup/signup.js
Labels: 매운맛🔥, 최종 제출

#88 [박민규] Sprint4
  css/login.css
  css/signup.css
  index.html
  js/api/ArticleService.js
  js/api/ProductService.js
  js/login.js
  js/main.js
  js/signup.js
  page/login.html
  page/signup.html
Labels: 매운맛🔥, 최종 제출

#50 Revert "[양성경] Sprint 1 & 2"
  mission1_SKY/faq.html
  mission1_SKY/img/Component 2@2x.png
  mission1_SKY/img/Component 2@3x.png
  mission1_SKY/img/Component 3@2x.png
  mission1_SKY/img/Component 3@3x.png
  mission1_SKY/img/Img_home1.png
  mission1_SKY/img/Img_home2.png
  mission1_SKY/img/Img_home3.png
  mission1_SKY/img/Img_home_bottom.png
  mission1_SKY/img/Img_home_top.png
  mission1_SKY/img/Img_reply_empty.png
  mission1_SKY/img/Typo.png
  mission1_SKY/img/eye-close.png
  mission1_SKY/img/eye-open.png
  mission1_SKY/img/google-img.png
  mission1_SKY/img/ic_back.png
  mission1_SKY/img/ic_facebook.png
  mission1_SKY/img/ic_instagram.png
  mission1_SKY/img/ic_search.png
  mission1_SKY/img/ic_twitter.png
  mission1_SKY/img/ic_youtube.png
  mission1_SKY/img/img_badge.png
  mission1_SKY/img/img_bottle.png
  mission1_SKY/img/img_panda.png
  mission1_SKY/img/kakaotalk-img.png
  mission1_SKY/img/logo1.png
  mission1_SKY/img/logo2.png
  mission1_SKY/img/logo3.png
  mission1_SKY/img/size=large, _status=active.png
  mission1_SKY/img/size=large, _status=inactive.png
  mission1_SKY/img/size=large.png
  mission1_SKY/img/size=medium, _status=active.png
  mission1_SKY/img/size=medium, _status=inactive.png
  mission1_SKY/img/size=medium.png
  mission1_SKY/img/size=small,_status=default-1.png
  mission1_SKY/img/size=small,_status=default.png
  mission1_SKY/img/size=small.png
  mission1_SKY/img/status=active-1.png
  mission1_SKY/img/status=active.png
  mission1_SKY/img/status=inactive-1.png
  mission1_SKY/img/status=inactive.png
  mission1_SKY/img/status=white-1.png
  mission1_SKY/img/status=white.png
  mission1_SKY/index.html
  mission1_SKY/items.html
  mission1_SKY/login.html
  mission1_SKY/privacy.html
  mission1_SKY/readme.md
  mission1_SKY/scripts/script.js
  mission1_SKY/signup.html
  mission1_SKY/styles/login.css
  mission1_SKY/styles/reset.css
  mission1_SKY/styles/style.css
Labels: 매운맛🔥, 진행 중 🏃
